export const bankConfigs = {
  hsbc: {
    id: "hsbc",
    name: "HSBC UK",
    code: "HBUKGB4B",
    logo: "/logos/hsbc.jpg",
    bankFullName: "HSBC UK BANK PLC",
    address: "AYLESBURY, MARKET SQUARE, 8 MARKET SQUARE, AYLESBURY, HP 20 1TW, UK",
    receiverBank: "BANK NEGARA INDONESIA - PT (PERSERO)",
    receiverAddress: "BNI BUILDING, FLOOR 7, JALAN JENDERAL SUDIRMAN 1, JAKARTA, INDONESIA",
    country: "UK",
    template: "hsbc",
    color: "red",
    accentColor: "from-red-600 to-red-700",
  },
  bni: {
    id: "bni",
    name: "BNI Indonesia",
    code: "BNINIDJA",
    logo: "/logos/bni.png",
    bankFullName: "PT BANK NEGARA INDONESIA TBK",
    address: "BNI BUILDING, JALAN JENDERAL SUDIRMAN, JAKARTA",
    receiverBank: "PT BANK NEGARA INDONESIA TBK",
    receiverAddress: "KCU KEDIRI, JL. BRAWIJAYA NO. 17, JAWA TIMUR",
    country: "Indonesia",
    template: "bni",
    color: "blue",
    accentColor: "from-blue-600 to-blue-700",
  },
  deutsche: {
    id: "deutsche",
    name: "Deutsche Bank",
    code: "DEUTDEFF9925",
    logo: "/logos/deutsche.png",
    bankFullName: "DEUTSCHE BANK AG",
    address: "TAUNUSANLAFE 12, 60325 FRANKFURT AM MAIN 60254",
    receiverBank: "DEUTSCHE BANK AG",
    receiverAddress: "TAUNUSANLAFE 12, 60325 FRANKFURT AM MAIN 60254",
    country: "Germany",
    template: "deutsche",
    color: "blue",
    accentColor: "from-blue-800 to-blue-900",
  },
  deutsche_v2: {
    id: "deutsche_v2",
    name: "Deutsche Bank V2",
    code: "DEUTDEFF9925",
    logo: "/logos/deutsche.png",
    bankFullName: "DEUTSCHE BANK AG",
    address: "TAUNUSANLAGE 12, 60325 FRANKFURT AM MAIN GERMANY",
    receiverBank: "PT BANK RAKYAT INDONESIA (PERSERO) TBK.",
    receiverAddress: "BANK BRI UNIT SEMPLAK JL. RAYA SEMPLAK NO.36, RT.02/RW.01 SEMPLAK, KEC. BOGOR BAR.",
    country: "Germany",
    template: "deutsche_v2",
    color: "blue",
    accentColor: "from-cyan-700 to-blue-900",
  },
  mandiri: {
    id: "mandiri",
    name: "Bank Mandiri",
    code: "BMRIIDJA",
    logo: "/logos/mandiri.png",
    bankFullName: "PT BANK MANDIRI (PERSERO) TBK",
    address: "JALAN JENDERAL GATOT SUBROTO KAV 36, JAKARTA",
    receiverBank: "PT BANK MANDIRI (PERSERO) TBK",
    receiverAddress: "JALAN JENDERAL GATOT SUBROTO KAV 36, JAKARTA",
    country: "Indonesia",
    template: "mandiri",
    color: "orange",
    accentColor: "from-orange-600 to-orange-700",
  },
  bca: {
    id: "bca",
    name: "BCA",
    code: "BCAIIDJA",
    logo: "/logos/bca.png",
    bankFullName: "PT BANK CENTRAL ASIA TBK",
    address: "JALAN MH THAMRIN NO 1, JAKARTA",
    receiverBank: "PT BANK CENTRAL ASIA TBK",
    receiverAddress: "JALAN MH THAMRIN NO 1, JAKARTA",
    country: "Indonesia",
    template: "bca",
    color: "blue",
    accentColor: "from-blue-500 to-blue-600",
  },
  citi: {
    id: "citi",
    name: "CitiBank",
    code: "CITIIDJX",
    logo: "/logos/citi.png",
    bankFullName: "CITIBANK NA",
    address: "JALAN JENDERAL SUDIRMAN KAV 54-55, JAKARTA",
    receiverBank: "CITIBANK NA",
    receiverAddress: "JALAN JENDERAL SUDIRMAN KAV 54-55, JAKARTA",
    country: "Indonesia",
    template: "citi",
    color: "blue",
    accentColor: "from-blue-700 to-blue-800",
  },
  standard: {
    id: "standard",
    name: "Standard Chartered",
    code: "SCBLIDJX",
    logo: "/logos/standard.png",
    bankFullName: "STANDARD CHARTERED BANK",
    address: "JALAN JENDERAL SUDIRMAN KAV 33A, JAKARTA",
    receiverBank: "STANDARD CHARTERED BANK",
    receiverAddress: "JALAN JENDERAL SUDIRMAN KAV 33A, JAKARTA",
    country: "Indonesia",
    template: "standard",
    color: "blue",
    accentColor: "from-blue-600 to-indigo-600",
  },
  dbs: {
    id: "dbs",
    name: "DBS Bank",
    code: "DBSSIDJX",
    logo: "/logos/dbs.png",
    bankFullName: "DBS BANK LTD",
    address: "12 MARINA BOULEVARD, SINGAPORE",
    receiverBank: "DBS BANK LTD",
    receiverAddress: "12 MARINA BOULEVARD, SINGAPORE",
    country: "Singapore",
    template: "dbs",
    color: "red",
    accentColor: "from-red-600 to-red-700",
  },
};

export const bankOptions = Object.values(bankConfigs).map((bank) => ({
  id: bank.id,
  name: bank.name,
}));

export const getBankConfig = (bankId) => {
  return bankConfigs[bankId] || bankConfigs.hsbc;
};
